apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-web-app
  name: docker-web-app-service
  
spec:
  clusterIP: 10.75.242.247
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32305
    port: 8090
    protocol: TCP
    targetPort: 8080
  selector:
    app: docker-web-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.76.205.235
