apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-12-29T17:48:25Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2020-12-29T19:28:11Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: docker-web-app
  name: docker-web-app-service
  namespace: default
  resourceVersion: "3276614"
  selfLink: /api/v1/namespaces/default/services/docker-web-app-service
  uid: b41379cc-0151-4e4a-af5a-38b6bcd89af0
spec:
  clusterIP: 10.75.242.247
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32305
    port: 8090
    protocol: TCP
    targetPort: 8080
  selector:
    app: docker-web-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.76.205.235
